# Generated by Django 2.1.7 on 2019-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(default='img/cat1.jpg', upload_to=''),
        ),
    ]
