# Generated by Django 2.1.7 on 2019-03-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(default='catimage/cat1.jpg', upload_to=''),
        ),
    ]
